#spring.application.name=iaparatodos-backend
#
#spring.datasource.url=jdbc:mysql://localhost:3306/iaparatodos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=always
#
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#
#app.admin.username=admin
#app.admin.password=admin123
#app.jwt.expiration-ms=86400000

###DEVELOPMENT


##--------------------------------------------------------------------------------
##---------------------------------PRODUCCION------------------------------------
##
spring.application.name=iaparatodos-backend

spring.datasource.url=${IAP_DATASOURCE_URL}
spring.datasource.username=${IAP_DATASOURCE_USERNAME}
spring.datasource.password=${IAP_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

server.error.include-message=always
server.error.include-binding-errors=never
server.error.include-stacktrace=never

logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
logging.level.com.iaparatodos.backend=ERROR

app.jwt.expiration-ms=86400000