package com.iaparatodos.backend.enums;

public enum NivelEducativo {
    PRIMARIO_INCOMPLETO,
    PRIMARIO_COMPLETO,
    SECUNDARIO_INCOMPLETO,
    SECUNDARIO_COMPLETO,
    TERCIARIO_UNIVERSITARIO_EN_CURSO,
    TERCIARIO_UNIVERSITARIO_COMPLETO,
    POSGRADO
}